# Generated by Django 4.1.3 on 2022-11-18 16:09

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.models.MyUserManager()),
            ],
        ),
    ]
